= Ethernet CPL Library for Arduino =

With the Qualcomm QCA7000 CPL Shield, this library allows an Witty Knowledge board (Arduino Due compatible) to connect to the internet.

For more information about this library please visit us at
https://www.wittyknowledge.com (developer)
or contact ERCTEEL company
http://www.ercteel.com/ (owner)

== License ==

Copyright (c) 2017 ERCTEEL. All right reserved.

This library is free software; you can redistribute it and/or
modify it under the terms of the GNU Lesser General Public
License as published by the Free Software Foundation; either
version 2.1 of the License, or (at your option) any later version.

This library is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
Lesser General Public License for more details.

You should have received a copy of the GNU Lesser General Public
License along with this library; if not, write to the Free Software
Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA
